# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
sys.path.insert(0, os.path.abspath('.'))
sys.path.insert(0, '/home/ace/Bureau/IPSA_Formation_GIT/src')
sys.path.insert(0, '/home/ace/Bureau/IPSA_Formation_GIT/logs')
sys.path.insert(0, '/home/ace/Bureau/IPSA_Formation_GIT/config')

# -- Project information -----------------------------------------------------

project = 'Git Workshop'
copyright = '2023, Alexandre Condette'
author = 'Alexandre Condette'

# The full version, including alpha/beta/rc tags
release = '0.0.1'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.autodoc',
'sphinx.ext.doctest',
'sphinx.ext.intersphinx',
'sphinx.ext.todo',
'sphinx.ext.coverage',
'sphinx.ext.mathjax',
'sphinx.ext.ifconfig',
'sphinx.ext.viewcode',
'recommonmark',
'sphinx.ext.autosectionlabel',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['.templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
source_suffix = ['.rst', '.md']
master_doc = 'index'

pygments_style = 'sphinx'
todo_icnlude_todos = True
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'fr'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'

project = u'GitHub Workshop'
author = u'Alexandre Condette'
# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = []

latex_elements={}

latex_documents= [
(master_doc, project, u'Documentation',
author, 'manual'),]

man_pages = [
(master_doc, project, u'Documentation',
[author], 1),]

textinfo_documents = [
(master_doc, project, u'Documentation',
author, project, 'manual', 'misc'),]

source_parsers = {
'.md': 'recommonmark.parser.CommonMarkParser'}
